<a href="https://colab.research.google.com/github/yogeshgujjar/hero-no-1/blob/main/project_DLBM_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("/content/matches.csv")
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [6]:
df.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [7]:
# Fill missing 'city' with most frequent city
df['city'].fillna(df['city'].mode()[0], inplace=True)

# Fill 'player_of_match' with 'Unknown'
df['player_of_match'].fillna('Unknown', inplace=True)

# Fill 'winner' with 'No Result'
df['winner'].fillna('No Result', inplace=True)

# Fill 'result_margin' with 0
df['result_margin'].fillna(0, inplace=True)

# Fill 'target_runs' and 'target_overs' with median
df['target_runs'].fillna(df['target_runs'].median(), inplace=True)
df['target_overs'].fillna(df['target_overs'].median(), inplace=True)

# Drop the 'method' column
df.drop('method', axis=1, inplace=True)

print("Missing values handled successfully ✅")

Missing values handled successfully ✅

<ipython-input-7-ae87ee48c413>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna(df['city'].mode()[0], inplace=True)
<ipython-input-7-ae87ee48c413>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['player_of_match'].fillna('Unknown', inplace=True)
<ipython-input-7-ae87ee48c413>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['winner'].fillna('No Result', inplace=True)
<ipython-input-7-ae87ee48c413>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['result_margin'].fillna(0, inplace=True)
<ipython-input-7-ae87ee48c413>:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['target_runs'].fillna(df['target_runs'].median(), inplace=True)
<ipython-input-7-ae87ee48c413>:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['target_overs'].fillna(df['target_overs'].median(), inplace=True)

In [8]:
df.shape

(1095, 19)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1095 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1095 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1095 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1095 non-null   float64
 14  target_runs      1095 non-null   float64
 15  target_overs     1095 non-null   float64
 16  super_over       1095 non-null   object
 17  umpire1          1095 non-null   object
 18  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(15)
memory usage: 162.7+ KB

In [10]:
df.drop(['id', 'player_of_match', 'result', 'result_margin', 'umpire1', 'umpire2', 'date'], axis=1, inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         1095 non-null   object
 1   city           1095 non-null   object
 2   match_type     1095 non-null   object
 3   venue          1095 non-null   object
 4   team1          1095 non-null   object
 5   team2          1095 non-null   object
 6   toss_winner    1095 non-null   object
 7   toss_decision  1095 non-null   object
 8   winner         1095 non-null   object
 9   target_runs    1095 non-null   float64
 10  target_overs   1095 non-null   float64
 11  super_over     1095 non-null   object
dtypes: float64(2), object(10)
memory usage: 102.8+ KB

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [13]:
teams = pd.concat([df['team1'], df['team2'], df['toss_winner']]).unique()

team_encoder = LabelEncoder()
team_encoder.fit(teams)

df['team1'] = team_encoder.transform(df['team1'])
df['team2'] = team_encoder.transform(df['team2'])
df['toss_winner'] = team_encoder.transform(df['toss_winner'])

In [14]:
df['toss_decision'] = df['toss_decision'].map({'bat': 1, 'field': 0})
df['super_over'] = df['super_over'].map({'Y': 1, 'N': 0})
season_encoder = LabelEncoder()
df['season'] = season_encoder.fit_transform(df['season'])

df['batting_first'] = np.where(df['toss_decision'] == 1, 1, 0)

In [15]:
df.head()

,season,city,match_type,venue,team1,team2,toss_winner,toss_decision,winner,target_runs,target_overs,super_over,batting_first
0,0,Bangalore,League,M Chinnaswamy Stadium,16,8,16,0,Kolkata Knight Riders,223.0,20.0,0,0
1,0,Chandigarh,League,"Punjab Cricket Association Stadium, Mohali",6,0,0,1,Chennai Super Kings,241.0,20.0,0,1
2,0,Delhi,League,Feroz Shah Kotla,3,13,13,1,Delhi Daredevils,130.0,20.0,0,1
3,0,Mumbai,League,Wankhede Stadium,10,16,10,1,Royal Challengers Bangalore,166.0,20.0,0,1
4,0,Kolkata,League,Eden Gardens,8,1,1,1,Kolkata Knight Riders,111.0,20.0,0,1

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   season         1095 non-null   int64
 1   city           1095 non-null   object
 2   match_type     1095 non-null   object
 3   venue          1095 non-null   object
 4   team1          1095 non-null   int64
 5   team2          1095 non-null   int64
 6   toss_winner    1095 non-null   int64
 7   toss_decision  1095 non-null   int64
 8   winner         1095 non-null   object
 9   target_runs    1095 non-null   float64
 10  target_overs   1095 non-null   float64
 11  super_over     1095 non-null   int64
 12  batting_first  1095 non-null   int64
dtypes: float64(2), int64(7), object(4)
memory usage: 111.3+ KB

In [17]:
df.shape

(1095, 13)

In [18]:
from sklearn.preprocessing import LabelEncoder

# Encode Venue (stadium)
venue_encoder = LabelEncoder()
df['venue'] = venue_encoder.fit_transform(df['venue'])

# Encode City
city_encoder = LabelEncoder()
df['city'] = city_encoder.fit_transform(df['city'])


# Initialize label encoder
encoder = LabelEncoder()

# Encoding 'winner' column (target variable)
df['winner'] = encoder.fit_transform(df['winner'])

# Encoding 'match_type' column (categorical variable)
df['match_type'] = encoder.fit_transform(df['match_type'])

# Check the data after encoding


# Now, X = Features (all columns except 'winner')
X = df.drop('winner', axis=1)

y = df['winner']

In [19]:
df.head()

,season,city,match_type,venue,team1,team2,toss_winner,toss_decision,winner,target_runs,target_overs,super_over,batting_first
0,0,2,4,23,16,8,16,0,8,223.0,20.0,0,0
1,0,7,4,40,6,0,0,1,0,241.0,20.0,0,1
2,0,10,4,16,3,13,13,1,3,130.0,20.0,0,1
3,0,26,4,55,10,16,10,1,17,166.0,20.0,0,1
4,0,23,4,14,8,1,1,1,8,111.0,20.0,0,1

In [24]:
from sklearn.model_selection import train_test_split

# Suppose X and y are your features and target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import accuracy_score

# Define the deep learning model architecture
model = Sequential()

# Input layer and first hidden layer
model.add(Dense(64, activation='relu', input_dim = X_train.shape[1]))

# Second hidden layer
model.add(Dense(32, activation='relu'))

# Output layer (binary classification, so we use sigmoid)
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Summary of the model
model.summary()

# Train the model
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Evaluate the model
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)  # Convert probabilities to binary outcomes (0 or 1)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Model Accuracy: {accuracy*100:.2f}%')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.0788 - loss: -90.4694 - val_accuracy: 0.0137 - val_loss: -893.6639
Epoch 2/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0272 - loss: -1223.7856 - val_accuracy: 0.0137 - val_loss: -2484.5933
Epoch 3/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0355 - loss: -3054.7622 - val_accuracy: 0.0137 - val_loss: -5586.5845
Epoch 4/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0180 - loss: -6628.9438 - val_accuracy: 0.0137 - val_loss: -11305.6836
Epoch 5/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0282 - loss: -13265.6777 - val_accuracy: 0.0137 - val_loss: -20883.7559
Epoch 6/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0333 - loss: -23885.8203 - val_accuracy: 0.0137 - val_loss: -35913.3125
Epoch 7/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0360 - loss: -41237.1211 - val_accuracy: 0.0137 - val_loss: -58525.4844
Epoch 8/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0232 - loss: -67142.9609 - val_accuracy: 0.0137 - val_loss: -89433.5156
Epoch 9/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0288 - loss: -99627.6250 - val_accuracy: 0.0137 - val_loss: -130940.3125
Epoch 10/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0293 - loss: -140111.2031 - val_accuracy: 0.0137 - val_loss: -184603.7188
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
Model Accuracy: 1.37%